// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 84wxoth5npGrp6RRXPL88z
import * as React from "react";

export default function GlobalContextsProvider(props) {}
