// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
// import * as React from "react";
import { PlasmicCardsDiv } from "./plasmic/akyllers/PlasmicCardsDiv";
import { render } from 'react-dom'


function CardsDiv_(props, ref) {





  
  return (
    
  <PlasmicCardsDiv root={{ ref }} {...props} />);
}

const CardsDiv = React.forwardRef(CardsDiv_);

export default CardsDiv;
