// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicGalleryItemBox } from "./plasmic/akyllers/PlasmicGalleryItemBox";

function GalleryItemBox_(props, ref) {
  // Use PlasmicGalleryItemBox to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicGalleryItemBox are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all GalleryItemBoxProps here, but feel free
  // to do whatever works for you.
  return <PlasmicGalleryItemBox root={{ ref }} {...props} />;
}

const GalleryItemBox = React.forwardRef(GalleryItemBox_);

export default GalleryItemBox;
