// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useState, useEffect } from "react"
import { PlasmicHomepage2 } from "../components/plasmic/akyllers/PlasmicHomepage2";
import TeamItemBox from "../components/TeamItemBox";

function Homepage2() {
  const [resources, setResources] = useState([]);

  useEffect(() => {
    var airtable_url = "https://api.airtable.com/v0/appaMdZWgP7E2X944/Team?api_key=" + "key5t3q3H8TgvBOMs"
    fetch(airtable_url)
      .then((res) => res.json())
      .then((resources) => {
        setResources(resources);
        console.log(resources);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  if (resources.records) {
  return (<PlasmicHomepage2
    photos={{
      children: resources.records.map((item) => {
        return (
          <TeamItemBox
            image={item.fields.Image[0].url}
            url={item.fields.url}
            title={item.fields.Title}
            job={item.fields.Job}
            description={item.fields.Description}
          />
        )
      })
    }}
    />)
}
return (<PlasmicHomepage2 />)}

export default Homepage2;
