// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useState, useEffect } from "react"
import { PlasmicManifesto6 } from "../components/plasmic/akyllers/PlasmicManifesto6";
import NewArt from "../components/NewArt";

function Manifesto6() {
  const [resources, setResources] = useState([]);

  useEffect(() => {
    var airtable_url = "https://api.airtable.com/v0/appaMdZWgP7E2X944/NewArt?api_key=" + "key5t3q3H8TgvBOMs"
    fetch(airtable_url)
      .then((res) => res.json())
      .then((resources) => {
        setResources(resources);
        console.log(resources);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  if (resources.records) {
  return (<PlasmicManifesto6
    artStack={{
      children: resources.records.map((item) => {
        return (
          <NewArt
            image={item.fields.Image[0].url}
            url={item.fields.url}
            title={item.fields.Title}
            description={item.fields.Description}
          />
        )
      })
    }}
    />);
} return (<PlasmicManifesto6 />)}

export default Manifesto6;
