// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cELQgcBTCpXC8URn4hyouo
// Component: lEWLrQK3dc
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_akyllers.module.css"; // plasmic-import: cELQgcBTCpXC8URn4hyouo/projectcss
import sty from "./PlasmicRoadmapItem.module.css"; // plasmic-import: lEWLrQK3dc/css

export const PlasmicRoadmapItem__VariantProps = new Array();

export const PlasmicRoadmapItem__ArgProps = new Array("link", "children");

export const defaultRoadmapItem__Args = {};

function PlasmicRoadmapItem__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultRoadmapItem__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
      component={Link}
      href={args.link}
      platform={"nextjs"}
    >
      <div className={classNames(projectcss.all, sty.freeBox___19HoC)}>
        <div className={classNames(projectcss.all, sty.freeBox__eee1U)}>
          {p.renderPlasmicSlot({
            defaultContents: "Enter some text",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </div>
      </div>
    </p.PlasmicLink>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRoadmapItem__ArgProps,
      internalVariantPropNames: PlasmicRoadmapItem__VariantProps
    });

    return PlasmicRoadmapItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRoadmapItem";
  } else {
    func.displayName = `PlasmicRoadmapItem.${nodeName}`;
  }
  return func;
}

export const PlasmicRoadmapItem = Object.assign(
  // Top-level PlasmicRoadmapItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRoadmapItem
    internalVariantProps: PlasmicRoadmapItem__VariantProps,
    internalArgProps: PlasmicRoadmapItem__ArgProps
  }
);

export default PlasmicRoadmapItem;
/* prettier-ignore-end */
