// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cELQgcBTCpXC8URn4hyouo
// Component: U1TWkuZvfI
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_akyllers.module.css"; // plasmic-import: cELQgcBTCpXC8URn4hyouo/projectcss
import sty from "./PlasmicLightFooterBox.module.css"; // plasmic-import: U1TWkuZvfI/css

export const PlasmicLightFooterBox__VariantProps = new Array();

export const PlasmicLightFooterBox__ArgProps = new Array("url");

export const defaultLightFooterBox__Args = {};

function PlasmicLightFooterBox__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultLightFooterBox__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
      component={Link}
      href={args.url}
      platform={"nextjs"}
      target={"_blank"}
    >
      <div
        data-plasmic-name={"lightFooterBox"}
        data-plasmic-override={overrides.lightFooterBox}
        className={classNames(projectcss.all, sty.lightFooterBox)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"DISCORD"}
        </div>
      </div>
    </p.PlasmicLink>
  );
}

const PlasmicDescendants = {
  root: ["root", "lightFooterBox", "text"],
  lightFooterBox: ["lightFooterBox", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLightFooterBox__ArgProps,
      internalVariantPropNames: PlasmicLightFooterBox__VariantProps
    });

    return PlasmicLightFooterBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLightFooterBox";
  } else {
    func.displayName = `PlasmicLightFooterBox.${nodeName}`;
  }
  return func;
}

export const PlasmicLightFooterBox = Object.assign(
  // Top-level PlasmicLightFooterBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    lightFooterBox: makeNodeComponent("lightFooterBox"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicLightFooterBox
    internalVariantProps: PlasmicLightFooterBox__VariantProps,
    internalArgProps: PlasmicLightFooterBox__ArgProps
  }
);

export default PlasmicLightFooterBox;
/* prettier-ignore-end */
