// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cELQgcBTCpXC8URn4hyouo
// Component: alRcFwfrdE
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_akyllers.module.css"; // plasmic-import: cELQgcBTCpXC8URn4hyouo/projectcss
import sty from "./PlasmicCardsDiv.module.css"; // plasmic-import: alRcFwfrdE/css

export const PlasmicCardsDiv__VariantProps = new Array();

export const PlasmicCardsDiv__ArgProps = new Array();

export const defaultCardsDiv__Args = {};

function PlasmicCardsDiv__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultCardsDiv__Args, props.args);
  const $props = args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCardsDiv__ArgProps,
      internalVariantPropNames: PlasmicCardsDiv__VariantProps
    });

    return PlasmicCardsDiv__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardsDiv";
  } else {
    func.displayName = `PlasmicCardsDiv.${nodeName}`;
  }
  return func;
}

export const PlasmicCardsDiv = Object.assign(
  // Top-level PlasmicCardsDiv renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCardsDiv
    internalVariantProps: PlasmicCardsDiv__VariantProps,
    internalArgProps: PlasmicCardsDiv__ArgProps
  }
);

export default PlasmicCardsDiv;
/* prettier-ignore-end */
